### ISSUE TITLE
Hello, how can I get vaccine information through SHC code?

### ISSUE THREAD

**Issue by lijianhui194** [StateOfCalifornia/DigitalCovid19VaccineRecord-API#20]

**Comment by christopher-eddy-state-ca-gov** [comment]
Hello,
1)Use this command line tool:  https://github.com/microsoft/health-cards-validation-SDK.git

2) command to use is:
 node . --type qrnumeric --path c:\qrnumeric.txt --loglevel debug
 
 Where qrnumeric.txt is a file with contents of shc:/1231212,........
