### ISSUE TITLE
Updating function according to readMe needs VcObject to have vc property

### ISSUE THREAD

**Issue by montyJordanIII** [StateOfCalifornia/DigitalCovid19VaccineRecord-API#24]
Should this property be created as well as the snowflake DB call removed for the GetVaccineCredentialSubjectAsync method?  I assume this is just for making this basic blueprint of this app functional without having to empower it with dynamic data.  

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SnowFlakeService.VcObject' does not contain a definition for 'vc' and no accessible extension method 'vc' accepting a first argument of type 'SnowFlakeService.VcObject' could be found (are you missing a using directive or an assembly reference?)	Infrastructure	D:\gitRepos\github\cali\dvcr\DigitalCovid19VaccineRecord-API\Infrastructure\SnowFlake\SnowFlakeService.cs	65	Active

**Comment by montyJordanIII** [comment]
> Should this property be created as well as the snowflake DB call removed for the GetVaccineCredentialSubjectAsync method? I assume this is just for making this basic blueprint of this app functional without having to empower it with dynamic data.
> 
> Severity Code Description Project File Line Suppression State Error CS1061 'SnowFlakeService.VcObject' does not contain a definition for 'vc' and no accessible extension method 'vc' accepting a first argument of type 'SnowFlakeService.VcObject' could be found (are you missing a using directive or an assembly reference?) Infrastructure D:\gitRepos\github\cali\dvcr\DigitalCovid19VaccineRecord-API\Infrastructure\SnowFlake\SnowFlakeService.cs 65 Active

I think the readMe might need to updated to the following code snippet, just guessing.

`var jsonString1 = @"{ ""Vc"": { ""credentialSubject"": { ""fhirBundle"": { ""entry"": [ { ""fullUrl"": ""resource:0"", ""resource"": { ""birthDate"": ""1951-08-15"", ""name"": [ { ""family"": ""Doe"", ""given"": [""John""] } ], ""resourceType"": ""Patient"" } }, { ""fullUrl"": ""resource:1"", ""resource"": { ""occurrenceDateTime"": ""2021-02-23"", ""patient"": { ""reference"": ""resource:0"" }, ""performer"": [ { ""actor"": { ""display"": ""KAISER PERMANENTE NCAL"" } } ], ""resourceType"": ""Immunization"", ""status"": ""completed"", ""vaccineCode"": { ""coding"": [ { ""code"": ""208"", ""system"": ""http://hl7.org/fhir/sid/cvx"" } ] } } }, { ""fullUrl"": ""resource:2"", ""resource"": { ""lotNumber"": ""EN6207"", ""occurrenceDateTime"": ""2021-03-16"", ""patient"": { ""reference"": ""resource:0"" }, ""performer"": [ { ""actor"": { ""display"": ""KAISER PERMANENTE NCAL"" } } ], ""resourceType"": ""Immunization"", ""status"": ""completed"", ""vaccineCode"": { ""coding"": [ { ""code"": ""208"", ""system"": ""http://hl7.org/fhir/sid/cvx"" } ] } } } ], ""resourceType"": ""Bundle"", ""type"": ""collection"" }, ""fhirVersion"": ""4.0.1"" }, ""type"": [ ""https://smarthealth.cards#health-card"", ""https://smarthealth.cards#immunization"", ""https://smarthealth.cards#covid19"" ] } }";

            var vaccineCredentialobject1 = JsonConvert.DeserializeObject<VcObject>(jsonString1);

            vaccineCredential = vaccineCredentialobject1.Vc;`

**Comment by Thuy-Ly** [comment]
Hi @montyJordanIII,

In the SnowflakeService.cs, the VcObject.Vc has json property attribute specified as vc, the JsonConvert should not have problem in deserializing it. I just confirmed it still works in my local dev.

```
class VcObject
        {
            [JsonProperty("vc")]
            public Vc Vc { get; set; }
        }
```

**Comment by montyJordanIII** [comment]
It is the editor that is complaining about a problem.  Are your code reviewing extensions less stringent then default visual studio?

**Comment by Thuy-Ly** [comment]
I do not believe we have any special extensions other than the default.
